// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConwayGameOfLife.Infrastructure.Models;

public partial class Board
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Cell> Cells { get; set; } = new List<Cell>();
}