// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace ConwayGameOfLife.Infrastructure.Models;

public partial class Cell
{
    public Guid Id { get; set; }

    public Guid BoardId { get; set; }

    public int RowPosition { get; set; }

    public int ColumnPosition { get; set; }

    public bool IsAlive { get; set; }

	[ForeignKey("BoardId")]
	[JsonIgnore]  // 
	public virtual Board Board { get; set; }
}