// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ConwayGameOfLife.Infrastructure.Models;

public partial class GameOfLifeDBContext : DbContext
{
    public GameOfLifeDBContext(DbContextOptions<GameOfLifeDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Board> Boards { get; set; }

    public virtual DbSet<Cell> Cells { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Board>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Boards__3214EC0703DE4E7D");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
          
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Cell>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Cells__3214EC070323AD57");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            

            entity.HasOne(d => d.Board).WithMany(p => p.Cells)
                .HasForeignKey(d => d.BoardId)
                .HasConstraintName("FK__Cells__BoardId__3F466844");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}